#pragma once

struct sprite;

enum resn : unsigned short {
	NONE,
	STONEBIG, REALMS, NORMAL, TOOLFONT, NUMBER,
	CURSORS, CURSARW, COLGRAD, COLOR,
	GACTN,
	GBTNBFRM, GBTNJBTN, GBTNLRG, GBTNMED, GBTNMED2, GBTNMINS, GBTNPLUS, GBTNOPT1, GBTNOPT2,
	GBTNSPB1, GBTNSPB2, GBTNSPB3,
	GBTNPOR, GUICONT, GUIMAP, GUIMAPWC, GUIHITPT, GUIREC, GBTNRECB, GBTNSCRL, GBTNSTD,
	GCOMM, GCOMMSB, GCOMMBTN, FLAG1,
	INVBUT2, INVBUT3, ITEMS, GROUND, CONTAINER, SCROLLS, FORM,
	// Characters
	CDMB1, CDMB2, CDMB3, CDMC4, CDMF4, CDMT1, CDMW1, CDMW2, CDMW3, CDMW4,
	CEFB1, CEFB2, CEFB3, CEFC4, CEFF4, CEFT1, CEFW1, CEFW2, CEFW3, CEFW4,
	CEMB1, CEMB2, CEMB3, CEMC4, CEMF4, CEMT1, CEMW1, CEMW2, CEMW3, CEMW4,
	CHFB1, CHFB2, CHFB3, CHFC4, CHFF4, CHFT1, CHFW1, CHFW2, CHFW3, CHFW4, CHFM1,
	CHMB1, CHMB2, CHMB3, CHMC4, CHMF4, CHMT1, CHMW1, CHMW2, CHMW3, CHMW4, CHMM1,
	CIFB1, CIFB2, CIFB3, CIFC4, CIFF4, CIFT1,
	CIMB1, CIMB2, CIMB3, CIMC4, CIMF4, CIMT1,
	GUIA, GUIBTACT, GUIBTBUT,
	GUICGB, GUICHP, GUIHELP, GUIFEAT, GUIINV,
	GIITMH08, GUIHSB, GUICARBB, GUISTDRB,
	GUIPFC, GUIRSPOR, GUISEX, GUISPL, GUICNAME, GUIERR,
	GUIRLVL, GMPMCHRB, GUISTMSC, GCGPARTY, GBTNLRG2,
	GUIJRLN, GOPT, GUIMOVB, STONEOPT, GUISRSVB, GUISTBBC, GUISRRQB, GUWBTP,
	CGEAR, ROOMS,
	LOAD, LOCATER,
	MAPICONS,
	PORTL, PORTS,
	SPELLS, SPLBUT, START, STON, STONSLOT,
	WMAP1, WMAP2, WMAP3,
	// Character weapons
	WQSAX, WQNAX, WQMAX, WQLAX,
	WQSBW, WQNBW, WQMBW, WQLBW,
	WQSCB, WQNCB, WQMCB, WQLCB,
	WQSD1, WQND1, WQMD1, WQLD1,
	WQSD2, WQND2, WQMD2, WQLD2,
	WQSD3, WQND3, WQMD3, WQLD3,
	WQSD4, WQND4, WQMD4, WQLD4,
	WQSDD, WQNDD, WQMDD, WQLDD,
	WQSFL, WQNFL, WQMFL, WQLFL,
	WQSH0, WQNH0, WQMH0, WQLH0,
	WQSH1, WQNH1, WQMH1, WQLH1,
	WQSH2, WQNH2, WQMH2, WQLH2,
	WQSH3, WQNH3, WQMH3, WQLH3,
	WQSH4, WQNH4, WQMH4, WQLH4,
	WQSH5, WQNH5, WQMH5, WQLH5,
	WQSHB, WQNHB, WQMHB, WQLHB,
	WQSMC, WQNMC, WQMMC, WQLMC,
	WQSQS, WQNQS, WQMQS, WQLQS,
	WQSS1, WQNS1, WQMS1, WQLS1,
	WQSS2, WQNS2, WQMS2, WQLS2,
	WQSS3, WQNS3, WQMS3, WQLS3,
	WQSSC, WQNSC, WQMSC, WQLSC,
	WQSSL, WQNSL, WQMSL, WQLSL,
	WQSSP, WQNSP, WQMSP, WQLSP,
	WQSSS, WQNSS, WQMSS, WQLSS,
	WQSWH, WQNWH, WQMWH, WQLWH,
	ARARROW, // Shoot and thrown
	MGO1, MSKA, MSKAA, // Monsters
};
struct residi {
	const char*	id;
	const char*	folder;
	sprite*		data;
	bool		error;
	void		clear();
	sprite*		get();
};
sprite* gres(resn i);
sprite* gres(const char* id, const char* folder);